[project]
name = "simple-django"
version = "0.1.0"
description = "Simple Django container app."
readme = "README.md"
requires-python = ">=3.9.21"
license = "MIT"
dependencies = [
    "django==4.2.11",
    "requests==2.32.0",
    "uwsgi==2.0.24",
]
